services:
  app:
    build: .
    container_name: bl_financeiro
    restart: always
    env_file:
      - .env
    networks:
      - mysql_shared
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - "traefik.http.routers.bl_financeiro.rule=Host(`${DOMAIN}`)"
      - traefik.http.routers.bl_financeiro.entrypoints=${TRAEFIK_ENTRYPOINT:-websecure}
      - traefik.http.routers.bl_financeiro.tls=true
      - traefik.http.routers.bl_financeiro.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-letsencrypt}
      - traefik.http.services.bl_financeiro.loadbalancer.server.port=8000

networks:
  mysql_shared:
    external: true
  traefik:
    external: true
